version: '3.8'


x-container-defaults:
  &defaults
  restart: always
  env_file:
    - .env


services:
  backend:
    <<: *defaults
    build:
      context: ./backend
      dockerfile: ./build/Dockerfile
    volumes:
      - ./backend:/code
    tty: true
    stdin_open: true
    networks:
      - default
    ports:
      - 8000:8000
    command: python src/manage.py runserver 0.0.0.0:8000

  db:
    <<: *defaults
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432


volumes:
  postgres_data:
